config/routes.rb
GDZLLA::Application.routes.draw do

  resources :users, except: [:index, :create] do
    resources :posts, only: [:index]
    get 'setup-flickr', action: 'setup_flickr', as: :setup_flickr_for, on: :member
  end
  get 'finish-flickr' => 'users#finish_flickr', as: :finish_flickr

  resources :posts, only: [:show, :create]

  get 'login' => 'sessions#new', as: :new_session
  get 'logout' => 'sessions#destroy', as: :destroy_session
  get 'oauth-callback' => 'sessions#create', as: :create_session

  post 'go/:service' => 'posts#create_from'
  post 'go' => 'posts#create'

  get 'about' => 'content#about'
  get 'help' => 'content#help'

  root to: 'content#index'

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :user_id,              type: Integer  # twitter id, to keep posts correlated when sn changes
  field :username,             type: String
  field :url_type,             type: Symbol,  default: :gdzlla
  field :strip_tags,           type: Boolean, default: false
  field :photoset,             type: String
  field :flickr_token,         type: String
  field :twitter_token,        type: String
  field :twitter_secret,       type: String

  has_many :posts, :dependent => :destroy

  index username: 1

  def to_param
    username
  end

  def flickr_token=(token)
    @flickr = nil
    @photosets = nil
    @flickr_token = token
  end

  def strip_tags?
    strip_tags
  end

  def twitter_token=(token)
    @twitter = nil
    @twitter_token = token
  end

  def twitter_secret=(secret)
    @twitter = nil
    @twitter_secret = secret
  end

  def photosets
    @photosets ||= flickr_client.photosets.get_list rescue nil
  end

  def timeline
    @timeline ||= twitter_client.user_timeline username
  end

  # protected

  def flickr_client
    client_opts = {key: GDZLLA.setting(:flickr_key), secret: GDZLLA.setting(:flickr_secret)}
    client_opts.merge!(token: flickr_token) unless flickr_token.blank?
    @flickr ||= Flickr.new(client_opts)
  end

  def twitter_client
    @twitter ||= Twitter::Client.new(oauth_token: twitter_token, oauth_token_secret: twitter_secret)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_user_from_url, only: [:show, :edit, :update, :destroy, :setup_flickr]
  before_filter :authentication_required, only: [:edit, :update, :destroy, :setup_flickr, :finish_flickr]
  before_filter :ensure_user_is_current_user, only: [:edit, :update, :destroy, :setup_flickr]

  def show
  end

  def new
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Account udpated!"
      redirect_to user_path @user
    else

    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "Welp. You deleted your account. Sorry to see you go!"
      redirect_to destroy_session_path
    else
      flash[:error] = "Bwahahahahhaha! Account deletion failed. Seriously though, I have no idea why."
      redirect_to user_path @user
    end
  end

  def setup_flickr
  end

  def finish_flickr
    @user = current_user
    @flickr = @user.flickr_client
    if params.include?(:frob)
      @flickr.auth.frob = params[:frob]
      @user.update_attribute(:flickr_token, @flickr.auth.token)
      flash[:success] = 'Flickr was successfully authorized!'
      redirect_to help_path
    else
      flash[:error] = 'Flickr failed to authorize :/'
      render :action => 'setup_flickr'
    end
  end

  protected

  def load_user_from_url
    @user = User.where(username: params[:id]).first
  end
end

app/views/users/_user_bar.html.erb
<div id="user_bar">
<% if signed_in? -%>
  <div id="user-bar-greeting">Hi, <%= link_to current_user.username, user_path(current_user) %>! (<%= link_to "Settings", edit_user_path(current_user) %>)</div>
  <div id="user-bar-action"  >
    <%= link_to "Log out", destroy_session_path %>
    &bull; <%= link_to "Halp!", help_path %>
    &bull; <%= link_to "About", about_path %></div>
<% else -%>
  <div id="user-bar-action"  ><%= link_to "Log in with twitter",  new_session_path %></div>
<% end -%>
</div>

app/views/users/authorize_flickr.html.erb
<% content_for :title, "Authorize flickr" %>
<% content_for :extra_class, "one-col"%>

<div id="two">
  <p>Next, you'll need to authorize us to post to your flickr account.</p>
  <div class="btn_black"><a href="<%= @flickr.auth.url(:write) %>">Authorize</a></div>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Your Account" %>
<% content_for :bodyclass, 'one-col settings' %>

<h2>Your account settings</h2>
<div class="settings-wrap">

  <%= form_for @user do |f| %>

    <ul class="more-options">
      <li><%= link_to '- Re-authorize flickr', setup_flickr_for_user_path(@user) %></li>
      <% if !@user.photosets.blank? %>
      <li><label for="default_photoset">- Use photoset:</label>
        <select id="default_photoset" name="user[photoset]">
          <option value="">---None---</option>
          <% @user.photosets.each do |photoset| %>
          <option value="<%= photoset.id %>" <% if @user.photoset == photoset.id %>selected<% end %>><%=h photoset.title %></option>
          <% end %>
          </select>
      </li>
      <% end %>
      <li><label for="url_type">- Short URL:</label>
          <select id="url_type" name="user[url_type]">
            <% Post.url_choices.each do |type, url| %>
            <option value="<%= type %>" <% if @user.url_type == type %>selected<% end %>><%=h url %></option>
            <% end %>
            </select>
        </li>
      <li><%= link_to("- Delete account", user_path(@user),
      :confirm => "Are you really, srsly sure you want to delete your account?",
      :method => :delete) %></li>
    </ul>

    <%= submit_tag 'Save Settings', :class => 'submit-btn' %>

  <% end %>
</div>

app/views/users/setup_flickr.html.erb
<% content_for :title, "Authorize flickr" %>
<% content_for :bodyclass, "one-col"%>

<div id="two">
  <p>Next, you'll need to authorize us to post to your flickr account.</p>
  <div class="btn_black"><a href="<%= @user.flickr_client.auth.url(:write) %>">Authorize</a></div>
</div>

app/views/users/show.html.erb
<% content_for :title, @user.username %>
<% content_for :bodyclass, 'one-col' %>
<div class="content">
<h2>
<% if current_user_is? @user %>
Your recent posts
<% else -%>
Recent posts from <a href="http://twitter.com/<%= @user.username %>" target="_blank"><%= @user.username %></a>
<% end -%>
</h2>
<ul class="posts">
<% if @user.posts.any? %>
    <% @user.posts.each do |post| %>
      <li><a href="<%= post.flickr_url %>"><img src="<%= post.thumb_url %>" alt="photo" title="Posted by <%= @user.username %>" /></a></li>
    <% end %>
<% else %>
    <p class="empty">
        <% if current_user_is? @user %>
        You haven't
        <% else -%>
        <%= @user.username %> hasn't
        <% end -%>
        posted any pictures yet!
    </p>
<% end %>
</ul>
</div>